/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SalesOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4180623690611570922L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SalesOrder\",\"namespace\":\"com.example\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"orderTimestamp\",\"type\":\"string\"},{\"name\":\"currency\",\"type\":\"string\"},{\"name\":\"orderTotal\",\"type\":\"string\"},{\"name\":\"customer\",\"type\":{\"type\":\"record\",\"name\":\"Customer\",\"fields\":[{\"name\":\"customerId\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"segment\",\"type\":\"string\"}]}},{\"name\":\"lineItems\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LineItem\",\"fields\":[{\"name\":\"lineItemId\",\"type\":\"string\"},{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"unitPrice\",\"type\":\"string\"},{\"name\":\"lineTotal\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SalesOrder> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SalesOrder> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SalesOrder> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SalesOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SalesOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SalesOrder to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SalesOrder from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SalesOrder instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SalesOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence orderId;
  private java.lang.CharSequence orderTimestamp;
  private java.lang.CharSequence currency;
  private java.lang.CharSequence orderTotal;
  private com.example.Customer customer;
  private java.util.List<com.example.LineItem> lineItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SalesOrder() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param orderTimestamp The new value for orderTimestamp
   * @param currency The new value for currency
   * @param orderTotal The new value for orderTotal
   * @param customer The new value for customer
   * @param lineItems The new value for lineItems
   */
  public SalesOrder(java.lang.CharSequence orderId, java.lang.CharSequence orderTimestamp, java.lang.CharSequence currency, java.lang.CharSequence orderTotal, com.example.Customer customer, java.util.List<com.example.LineItem> lineItems) {
    this.orderId = orderId;
    this.orderTimestamp = orderTimestamp;
    this.currency = currency;
    this.orderTotal = orderTotal;
    this.customer = customer;
    this.lineItems = lineItems;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return orderTimestamp;
    case 2: return currency;
    case 3: return orderTotal;
    case 4: return customer;
    case 5: return lineItems;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.CharSequence)value$; break;
    case 1: orderTimestamp = (java.lang.CharSequence)value$; break;
    case 2: currency = (java.lang.CharSequence)value$; break;
    case 3: orderTotal = (java.lang.CharSequence)value$; break;
    case 4: customer = (com.example.Customer)value$; break;
    case 5: lineItems = (java.util.List<com.example.LineItem>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'orderTimestamp' field.
   * @return The value of the 'orderTimestamp' field.
   */
  public java.lang.CharSequence getOrderTimestamp() {
    return orderTimestamp;
  }


  /**
   * Sets the value of the 'orderTimestamp' field.
   * @param value the value to set.
   */
  public void setOrderTimestamp(java.lang.CharSequence value) {
    this.orderTimestamp = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'orderTotal' field.
   * @return The value of the 'orderTotal' field.
   */
  public java.lang.CharSequence getOrderTotal() {
    return orderTotal;
  }


  /**
   * Sets the value of the 'orderTotal' field.
   * @param value the value to set.
   */
  public void setOrderTotal(java.lang.CharSequence value) {
    this.orderTotal = value;
  }

  /**
   * Gets the value of the 'customer' field.
   * @return The value of the 'customer' field.
   */
  public com.example.Customer getCustomer() {
    return customer;
  }


  /**
   * Sets the value of the 'customer' field.
   * @param value the value to set.
   */
  public void setCustomer(com.example.Customer value) {
    this.customer = value;
  }

  /**
   * Gets the value of the 'lineItems' field.
   * @return The value of the 'lineItems' field.
   */
  public java.util.List<com.example.LineItem> getLineItems() {
    return lineItems;
  }


  /**
   * Sets the value of the 'lineItems' field.
   * @param value the value to set.
   */
  public void setLineItems(java.util.List<com.example.LineItem> value) {
    this.lineItems = value;
  }

  /**
   * Creates a new SalesOrder RecordBuilder.
   * @return A new SalesOrder RecordBuilder
   */
  public static com.example.SalesOrder.Builder newBuilder() {
    return new com.example.SalesOrder.Builder();
  }

  /**
   * Creates a new SalesOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SalesOrder RecordBuilder
   */
  public static com.example.SalesOrder.Builder newBuilder(com.example.SalesOrder.Builder other) {
    if (other == null) {
      return new com.example.SalesOrder.Builder();
    } else {
      return new com.example.SalesOrder.Builder(other);
    }
  }

  /**
   * Creates a new SalesOrder RecordBuilder by copying an existing SalesOrder instance.
   * @param other The existing instance to copy.
   * @return A new SalesOrder RecordBuilder
   */
  public static com.example.SalesOrder.Builder newBuilder(com.example.SalesOrder other) {
    if (other == null) {
      return new com.example.SalesOrder.Builder();
    } else {
      return new com.example.SalesOrder.Builder(other);
    }
  }

  /**
   * RecordBuilder for SalesOrder instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SalesOrder>
    implements org.apache.avro.data.RecordBuilder<SalesOrder> {

    private java.lang.CharSequence orderId;
    private java.lang.CharSequence orderTimestamp;
    private java.lang.CharSequence currency;
    private java.lang.CharSequence orderTotal;
    private com.example.Customer customer;
    private com.example.Customer.Builder customerBuilder;
    private java.util.List<com.example.LineItem> lineItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.SalesOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderTimestamp)) {
        this.orderTimestamp = data().deepCopy(fields()[1].schema(), other.orderTimestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.currency)) {
        this.currency = data().deepCopy(fields()[2].schema(), other.currency);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.orderTotal)) {
        this.orderTotal = data().deepCopy(fields()[3].schema(), other.orderTotal);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.customer)) {
        this.customer = data().deepCopy(fields()[4].schema(), other.customer);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasCustomerBuilder()) {
        this.customerBuilder = com.example.Customer.newBuilder(other.getCustomerBuilder());
      }
      if (isValidValue(fields()[5], other.lineItems)) {
        this.lineItems = data().deepCopy(fields()[5].schema(), other.lineItems);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing SalesOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.SalesOrder other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderTimestamp)) {
        this.orderTimestamp = data().deepCopy(fields()[1].schema(), other.orderTimestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.currency)) {
        this.currency = data().deepCopy(fields()[2].schema(), other.currency);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.orderTotal)) {
        this.orderTotal = data().deepCopy(fields()[3].schema(), other.orderTotal);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customer)) {
        this.customer = data().deepCopy(fields()[4].schema(), other.customer);
        fieldSetFlags()[4] = true;
      }
      this.customerBuilder = null;
      if (isValidValue(fields()[5], other.lineItems)) {
        this.lineItems = data().deepCopy(fields()[5].schema(), other.lineItems);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderTimestamp' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderTimestamp() {
      return orderTimestamp;
    }


    /**
      * Sets the value of the 'orderTimestamp' field.
      * @param value The value of 'orderTimestamp'.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder setOrderTimestamp(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.orderTimestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderTimestamp' field has been set.
      * @return True if the 'orderTimestamp' field has been set, false otherwise.
      */
    public boolean hasOrderTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderTimestamp' field.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder clearOrderTimestamp() {
      orderTimestamp = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.currency = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderTotal' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderTotal() {
      return orderTotal;
    }


    /**
      * Sets the value of the 'orderTotal' field.
      * @param value The value of 'orderTotal'.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder setOrderTotal(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.orderTotal = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'orderTotal' field has been set.
      * @return True if the 'orderTotal' field has been set, false otherwise.
      */
    public boolean hasOrderTotal() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'orderTotal' field.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder clearOrderTotal() {
      orderTotal = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer' field.
      * @return The value.
      */
    public com.example.Customer getCustomer() {
      return customer;
    }


    /**
      * Sets the value of the 'customer' field.
      * @param value The value of 'customer'.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder setCustomer(com.example.Customer value) {
      validate(fields()[4], value);
      this.customerBuilder = null;
      this.customer = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'customer' field has been set.
      * @return True if the 'customer' field has been set, false otherwise.
      */
    public boolean hasCustomer() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'customer' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.example.Customer.Builder getCustomerBuilder() {
      if (customerBuilder == null) {
        if (hasCustomer()) {
          setCustomerBuilder(com.example.Customer.newBuilder(customer));
        } else {
          setCustomerBuilder(com.example.Customer.newBuilder());
        }
      }
      return customerBuilder;
    }

    /**
     * Sets the Builder instance for the 'customer' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.example.SalesOrder.Builder setCustomerBuilder(com.example.Customer.Builder value) {
      clearCustomer();
      customerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'customer' field has an active Builder instance
     * @return True if the 'customer' field has an active Builder instance
     */
    public boolean hasCustomerBuilder() {
      return customerBuilder != null;
    }

    /**
      * Clears the value of the 'customer' field.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder clearCustomer() {
      customer = null;
      customerBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'lineItems' field.
      * @return The value.
      */
    public java.util.List<com.example.LineItem> getLineItems() {
      return lineItems;
    }


    /**
      * Sets the value of the 'lineItems' field.
      * @param value The value of 'lineItems'.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder setLineItems(java.util.List<com.example.LineItem> value) {
      validate(fields()[5], value);
      this.lineItems = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'lineItems' field has been set.
      * @return True if the 'lineItems' field has been set, false otherwise.
      */
    public boolean hasLineItems() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'lineItems' field.
      * @return This builder.
      */
    public com.example.SalesOrder.Builder clearLineItems() {
      lineItems = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SalesOrder build() {
      try {
        SalesOrder record = new SalesOrder();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.orderTimestamp = fieldSetFlags()[1] ? this.orderTimestamp : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.currency = fieldSetFlags()[2] ? this.currency : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.orderTotal = fieldSetFlags()[3] ? this.orderTotal : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (customerBuilder != null) {
          try {
            record.customer = this.customerBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("customer"));
            throw e;
          }
        } else {
          record.customer = fieldSetFlags()[4] ? this.customer : (com.example.Customer) defaultValue(fields()[4]);
        }
        record.lineItems = fieldSetFlags()[5] ? this.lineItems : (java.util.List<com.example.LineItem>) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SalesOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<SalesOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SalesOrder>
    READER$ = (org.apache.avro.io.DatumReader<SalesOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    out.writeString(this.orderTimestamp);

    out.writeString(this.currency);

    out.writeString(this.orderTotal);

    this.customer.customEncode(out);

    long size0 = this.lineItems.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.example.LineItem e0: this.lineItems) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);

      this.orderTimestamp = in.readString(this.orderTimestamp instanceof Utf8 ? (Utf8)this.orderTimestamp : null);

      this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);

      this.orderTotal = in.readString(this.orderTotal instanceof Utf8 ? (Utf8)this.orderTotal : null);

      if (this.customer == null) {
        this.customer = new com.example.Customer();
      }
      this.customer.customDecode(in);

      long size0 = in.readArrayStart();
      java.util.List<com.example.LineItem> a0 = this.lineItems;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.example.LineItem>((int)size0, SCHEMA$.getField("lineItems").schema());
        this.lineItems = a0;
      } else a0.clear();
      SpecificData.Array<com.example.LineItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.example.LineItem>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.example.LineItem e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.example.LineItem();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
          break;

        case 1:
          this.orderTimestamp = in.readString(this.orderTimestamp instanceof Utf8 ? (Utf8)this.orderTimestamp : null);
          break;

        case 2:
          this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);
          break;

        case 3:
          this.orderTotal = in.readString(this.orderTotal instanceof Utf8 ? (Utf8)this.orderTotal : null);
          break;

        case 4:
          if (this.customer == null) {
            this.customer = new com.example.Customer();
          }
          this.customer.customDecode(in);
          break;

        case 5:
          long size0 = in.readArrayStart();
          java.util.List<com.example.LineItem> a0 = this.lineItems;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.example.LineItem>((int)size0, SCHEMA$.getField("lineItems").schema());
            this.lineItems = a0;
          } else a0.clear();
          SpecificData.Array<com.example.LineItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.example.LineItem>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.example.LineItem e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.example.LineItem();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










