nameOverride: "vision"
fullnameOverride: ""
bitnamiKafka:
  enabled: false
kafkaBootstrapServers: "kafka-prd.kafka.svc.cluster.local:9092"
schemaRegistry:
  enabled: true
producer:
  enabled: true
  replicas: 2
  image:
    repository: my-registry/pos-producer
    tag: 0.1.0
    pullPolicy: IfNotPresent
  intervalMs: 2500
  rawTopic: raw_sales_orders
processor:
  enabled: true
  replicas: 2
  image:
    repository: my-registry/pos-processor
    tag: 0.1.0
    pullPolicy: IfNotPresent
  consumerGroupId: realtime-flink-processor-prd
  checkpointIntervalMs: 5000
icebergWriter:
  enabled: false
controlCenter:
  enabled: false
minio:
  enabled: false
trino:
  enabled: false
postgres:
  enabled: false
odsConnect:
  enabled: false
  topicsDir: raw/ods
dbt:
  enabled: false
airflow:
  enabled: false
mdm:
  enabled: false
dbzConnect:
  enabled: false
conduktor:
  enabled: false
observability:
  enabled: false
openmetadata:
  enabled: false
zookeeper:
  enabled: false
kafka:
  enabled: false