/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LineItem extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2748174239402934541L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LineItem\",\"namespace\":\"com.example\",\"fields\":[{\"name\":\"lineItemId\",\"type\":\"string\"},{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"unitPrice\",\"type\":\"string\"},{\"name\":\"lineTotal\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LineItem> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LineItem> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LineItem> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LineItem> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LineItem> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LineItem to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LineItem from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LineItem instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LineItem fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence lineItemId;
  private java.lang.CharSequence sku;
  private java.lang.CharSequence productName;
  private int quantity;
  private java.lang.CharSequence unitPrice;
  private java.lang.CharSequence lineTotal;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LineItem() {}

  /**
   * All-args constructor.
   * @param lineItemId The new value for lineItemId
   * @param sku The new value for sku
   * @param productName The new value for productName
   * @param quantity The new value for quantity
   * @param unitPrice The new value for unitPrice
   * @param lineTotal The new value for lineTotal
   */
  public LineItem(java.lang.CharSequence lineItemId, java.lang.CharSequence sku, java.lang.CharSequence productName, java.lang.Integer quantity, java.lang.CharSequence unitPrice, java.lang.CharSequence lineTotal) {
    this.lineItemId = lineItemId;
    this.sku = sku;
    this.productName = productName;
    this.quantity = quantity;
    this.unitPrice = unitPrice;
    this.lineTotal = lineTotal;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return lineItemId;
    case 1: return sku;
    case 2: return productName;
    case 3: return quantity;
    case 4: return unitPrice;
    case 5: return lineTotal;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: lineItemId = (java.lang.CharSequence)value$; break;
    case 1: sku = (java.lang.CharSequence)value$; break;
    case 2: productName = (java.lang.CharSequence)value$; break;
    case 3: quantity = (java.lang.Integer)value$; break;
    case 4: unitPrice = (java.lang.CharSequence)value$; break;
    case 5: lineTotal = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'lineItemId' field.
   * @return The value of the 'lineItemId' field.
   */
  public java.lang.CharSequence getLineItemId() {
    return lineItemId;
  }


  /**
   * Sets the value of the 'lineItemId' field.
   * @param value the value to set.
   */
  public void setLineItemId(java.lang.CharSequence value) {
    this.lineItemId = value;
  }

  /**
   * Gets the value of the 'sku' field.
   * @return The value of the 'sku' field.
   */
  public java.lang.CharSequence getSku() {
    return sku;
  }


  /**
   * Sets the value of the 'sku' field.
   * @param value the value to set.
   */
  public void setSku(java.lang.CharSequence value) {
    this.sku = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.CharSequence getProductName() {
    return productName;
  }


  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'unitPrice' field.
   * @return The value of the 'unitPrice' field.
   */
  public java.lang.CharSequence getUnitPrice() {
    return unitPrice;
  }


  /**
   * Sets the value of the 'unitPrice' field.
   * @param value the value to set.
   */
  public void setUnitPrice(java.lang.CharSequence value) {
    this.unitPrice = value;
  }

  /**
   * Gets the value of the 'lineTotal' field.
   * @return The value of the 'lineTotal' field.
   */
  public java.lang.CharSequence getLineTotal() {
    return lineTotal;
  }


  /**
   * Sets the value of the 'lineTotal' field.
   * @param value the value to set.
   */
  public void setLineTotal(java.lang.CharSequence value) {
    this.lineTotal = value;
  }

  /**
   * Creates a new LineItem RecordBuilder.
   * @return A new LineItem RecordBuilder
   */
  public static com.example.LineItem.Builder newBuilder() {
    return new com.example.LineItem.Builder();
  }

  /**
   * Creates a new LineItem RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LineItem RecordBuilder
   */
  public static com.example.LineItem.Builder newBuilder(com.example.LineItem.Builder other) {
    if (other == null) {
      return new com.example.LineItem.Builder();
    } else {
      return new com.example.LineItem.Builder(other);
    }
  }

  /**
   * Creates a new LineItem RecordBuilder by copying an existing LineItem instance.
   * @param other The existing instance to copy.
   * @return A new LineItem RecordBuilder
   */
  public static com.example.LineItem.Builder newBuilder(com.example.LineItem other) {
    if (other == null) {
      return new com.example.LineItem.Builder();
    } else {
      return new com.example.LineItem.Builder(other);
    }
  }

  /**
   * RecordBuilder for LineItem instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LineItem>
    implements org.apache.avro.data.RecordBuilder<LineItem> {

    private java.lang.CharSequence lineItemId;
    private java.lang.CharSequence sku;
    private java.lang.CharSequence productName;
    private int quantity;
    private java.lang.CharSequence unitPrice;
    private java.lang.CharSequence lineTotal;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.LineItem.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.lineItemId)) {
        this.lineItemId = data().deepCopy(fields()[0].schema(), other.lineItemId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sku)) {
        this.sku = data().deepCopy(fields()[1].schema(), other.sku);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productName)) {
        this.productName = data().deepCopy(fields()[2].schema(), other.productName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.quantity)) {
        this.quantity = data().deepCopy(fields()[3].schema(), other.quantity);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.unitPrice)) {
        this.unitPrice = data().deepCopy(fields()[4].schema(), other.unitPrice);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.lineTotal)) {
        this.lineTotal = data().deepCopy(fields()[5].schema(), other.lineTotal);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing LineItem instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.LineItem other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.lineItemId)) {
        this.lineItemId = data().deepCopy(fields()[0].schema(), other.lineItemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sku)) {
        this.sku = data().deepCopy(fields()[1].schema(), other.sku);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productName)) {
        this.productName = data().deepCopy(fields()[2].schema(), other.productName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.quantity)) {
        this.quantity = data().deepCopy(fields()[3].schema(), other.quantity);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.unitPrice)) {
        this.unitPrice = data().deepCopy(fields()[4].schema(), other.unitPrice);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lineTotal)) {
        this.lineTotal = data().deepCopy(fields()[5].schema(), other.lineTotal);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'lineItemId' field.
      * @return The value.
      */
    public java.lang.CharSequence getLineItemId() {
      return lineItemId;
    }


    /**
      * Sets the value of the 'lineItemId' field.
      * @param value The value of 'lineItemId'.
      * @return This builder.
      */
    public com.example.LineItem.Builder setLineItemId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.lineItemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'lineItemId' field has been set.
      * @return True if the 'lineItemId' field has been set, false otherwise.
      */
    public boolean hasLineItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'lineItemId' field.
      * @return This builder.
      */
    public com.example.LineItem.Builder clearLineItemId() {
      lineItemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sku' field.
      * @return The value.
      */
    public java.lang.CharSequence getSku() {
      return sku;
    }


    /**
      * Sets the value of the 'sku' field.
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public com.example.LineItem.Builder setSku(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.sku = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sku' field.
      * @return This builder.
      */
    public com.example.LineItem.Builder clearSku() {
      sku = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return productName;
    }


    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public com.example.LineItem.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.productName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public com.example.LineItem.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.example.LineItem.Builder setQuantity(int value) {
      validate(fields()[3], value);
      this.quantity = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.example.LineItem.Builder clearQuantity() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'unitPrice' field.
      * @return The value.
      */
    public java.lang.CharSequence getUnitPrice() {
      return unitPrice;
    }


    /**
      * Sets the value of the 'unitPrice' field.
      * @param value The value of 'unitPrice'.
      * @return This builder.
      */
    public com.example.LineItem.Builder setUnitPrice(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.unitPrice = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'unitPrice' field has been set.
      * @return True if the 'unitPrice' field has been set, false otherwise.
      */
    public boolean hasUnitPrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'unitPrice' field.
      * @return This builder.
      */
    public com.example.LineItem.Builder clearUnitPrice() {
      unitPrice = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'lineTotal' field.
      * @return The value.
      */
    public java.lang.CharSequence getLineTotal() {
      return lineTotal;
    }


    /**
      * Sets the value of the 'lineTotal' field.
      * @param value The value of 'lineTotal'.
      * @return This builder.
      */
    public com.example.LineItem.Builder setLineTotal(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.lineTotal = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'lineTotal' field has been set.
      * @return True if the 'lineTotal' field has been set, false otherwise.
      */
    public boolean hasLineTotal() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'lineTotal' field.
      * @return This builder.
      */
    public com.example.LineItem.Builder clearLineTotal() {
      lineTotal = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LineItem build() {
      try {
        LineItem record = new LineItem();
        record.lineItemId = fieldSetFlags()[0] ? this.lineItemId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.sku = fieldSetFlags()[1] ? this.sku : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.productName = fieldSetFlags()[2] ? this.productName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.quantity = fieldSetFlags()[3] ? this.quantity : (java.lang.Integer) defaultValue(fields()[3]);
        record.unitPrice = fieldSetFlags()[4] ? this.unitPrice : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.lineTotal = fieldSetFlags()[5] ? this.lineTotal : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LineItem>
    WRITER$ = (org.apache.avro.io.DatumWriter<LineItem>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LineItem>
    READER$ = (org.apache.avro.io.DatumReader<LineItem>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.lineItemId);

    out.writeString(this.sku);

    out.writeString(this.productName);

    out.writeInt(this.quantity);

    out.writeString(this.unitPrice);

    out.writeString(this.lineTotal);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.lineItemId = in.readString(this.lineItemId instanceof Utf8 ? (Utf8)this.lineItemId : null);

      this.sku = in.readString(this.sku instanceof Utf8 ? (Utf8)this.sku : null);

      this.productName = in.readString(this.productName instanceof Utf8 ? (Utf8)this.productName : null);

      this.quantity = in.readInt();

      this.unitPrice = in.readString(this.unitPrice instanceof Utf8 ? (Utf8)this.unitPrice : null);

      this.lineTotal = in.readString(this.lineTotal instanceof Utf8 ? (Utf8)this.lineTotal : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.lineItemId = in.readString(this.lineItemId instanceof Utf8 ? (Utf8)this.lineItemId : null);
          break;

        case 1:
          this.sku = in.readString(this.sku instanceof Utf8 ? (Utf8)this.sku : null);
          break;

        case 2:
          this.productName = in.readString(this.productName instanceof Utf8 ? (Utf8)this.productName : null);
          break;

        case 3:
          this.quantity = in.readInt();
          break;

        case 4:
          this.unitPrice = in.readString(this.unitPrice instanceof Utf8 ? (Utf8)this.unitPrice : null);
          break;

        case 5:
          this.lineTotal = in.readString(this.lineTotal instanceof Utf8 ? (Utf8)this.lineTotal : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










