realtime_analytics:
  target: trino
  outputs:
    dev:
      type: postgres
      host: snowflake-mimic
      port: 5432
      user: analytics
      password: analytics
      dbname: analytics
      schema: public
      threads: 4
    trino:
      type: trino
      user: analytics
      host: trino
      port: 8080
      catalog: lakehouse
      schema: streaming
      threads: 4