{{- if .Values.controlCenter.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "realtime-app.fullname" . }}-control-center
  labels:
    app.kubernetes.io/name: {{ include "realtime-app.name" . }}
    app.kubernetes.io/component: control-center
spec:
  replicas: {{ .Values.controlCenter.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "realtime-app.name" . }}
      app.kubernetes.io/component: control-center
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "realtime-app.name" . }}
        app.kubernetes.io/component: control-center
    spec:
      containers:
        - name: control-center
          image: {{ .Values.controlCenter.image.repository }}:{{ .Values.controlCenter.image.tag }}
          imagePullPolicy: {{ .Values.controlCenter.image.pullPolicy }}
          ports:
            - containerPort: 9021
          env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: {{ .Values.kafkaBootstrapServers | quote }}
            - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
              value: ""
            - name: CONTROL_CENTER_CONNECT_CONNECT_CLUSTER
              value: {{ .Values.controlCenter.connectCluster | quote }}
            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
              value: {{ .Values.controlCenter.schemaRegistryUrl | quote }}
            - name: CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT
              value: "/connectors"
            - name: CONTROL_CENTER_CONNECT_CLUSTER
              value: {{ .Values.controlCenter.connectClusterName | quote }}
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_COMMAND_TOPIC_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"
            - name: PORT
              value: "9021"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "realtime-app.fullname" . }}-control-center
  labels:
    app.kubernetes.io/name: {{ include "realtime-app.name" . }}
    app.kubernetes.io/component: control-center
spec:
  type: {{ .Values.controlCenter.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "realtime-app.name" . }}
    app.kubernetes.io/component: control-center
  ports:
    - name: http
      port: {{ .Values.controlCenter.service.port }}
      targetPort: 9021
{{- end }}
