apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vision.fullname" . }}-register-schemas-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: {{ include "vision.name" . }}
    app.kubernetes.io/component: schema-registry
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: register-schemas
          image: {{ .Values.schemaInit.image.repository }}:{{ .Values.schemaInit.image.tag }}
          imagePullPolicy: {{ .Values.schemaInit.image.pullPolicy }}
          env:
            - name: SCHEMA_REGISTRY_URL
              value: http://{{ include "vision.serviceName" (dict "root" . "key" "schema-registry") }}:8081
