apiVersion: v1
kind: ConfigMap
metadata:
  name: schemas-configmap
  labels:
    app.kubernetes.io/name: realtime-app
    app.kubernetes.io/component: schema-registry
data:
  # Example: Place your Avro/JSON schemas here as stringified JSON
  raw_sales_orders.json: |
    { "type": "record", "name": "RawSalesOrders", "fields": [{"name": "id", "type": "string"}] }
  sales_order.json: |
    { "type": "record", "name": "SalesOrder", "fields": [{"name": "id", "type": "string"}] }
  sales_order_line_item.json: |
    { "type": "record", "name": "SalesOrderLineItem", "fields": [{"name": "id", "type": "string"}] }
  customer_sales.json: |
    { "type": "record", "name": "CustomerSales", "fields": [{"name": "id", "type": "string"}] }
  mdm_customer.json: |
    { "type": "record", "name": "MdmCustomer", "fields": [{"name": "id", "type": "string"}] }
  mdm_product.json: |
    { "type": "record", "name": "MdmProduct", "fields": [{"name": "id", "type": "string"}] }
